name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  release:
    types: [published,prereleased]


env:
  IMAGE_NAME: picard
  DOCKER_HUB_REP_NAME: biotoolsdx


jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Run build tests
        run: |
          docker build . --file Dockerfile
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        run: |
          PACKAGE_VERSION=$(cat VERSION|head -n1 | sed 's/\n//g')
          docker build . --file Dockerfile -t ${IMAGE_NAME} --build-arg picard_version=${PACKAGE_VERSION}
      - name: Log into registry
        run: echo "${{ secrets.dockerhub_token }}" | docker login  -u ${{ secrets.dockerhub_user }} --password-stdin

      - name: Push image
        run: |
          PACKAGE_VERSION=$(cat VERSION|head -n1 | sed 's/\n//g')
          IMAGE_ID=${DOCKER_HUB_REP_NAME}/${IMAGE_NAME}
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$PACKAGE_VERSION
          docker push $IMAGE_ID:$PACKAGE_VERSION
